const Constants = {
  GENERIC_BACKGROUND: '#e2e7f1',
  CARD_BACKGROUND: '#ffffff',
  ICON_SIZE_SMALL: 20,
  ICON_SIZE_MEDIUM: 30,
  INPUT_BACKGROUND: '#e9eef8',
  INPUT_PLACEHOLDER_COLOR: '#8595aa',
  INPUT_COLOR: '#464f5a',
  BUTTON_BACKGROUND: '#6e62e4',
  BUTTON_COLOR: '#ffffff',
  NUMBER_PICKER_LABEL_COLOR: '#464f5a',
  NUMBER_PICKER_SELECTOR: '#b7bfc9',
  SEPARATOR_COLOR: '#b7bfc9',
  MODAL_BACKGROUND: '#00000080',
  CARD_BACKGROUND_STATUS_VOID: '#a4e0b4',
  CARD_BACKGROUND_STATUS_WORKING: '#a4b3e0',
  CARD_BACKGROUND_STATUS_END: '#e0a4ac',
};
export default Constants;
